#!/usr/bin/env node
/**
 * Generates src/countries/borders-data.ts: simplified ASEAN + Timor-Leste land polygons for
 * countryAt(lat, lon). Source: Natural Earth 1:10m admin-0 countries (public domain).
 *
 *   node scripts/make-borders.mjs [path/to/ne_10m_admin_0_countries.geojson]
 *
 * Without an argument the GeoJSON is downloaded from the natural-earth-vector repo.
 * Douglas-Peucker tolerance 0.02° (SG 0.005°), polygons under 0.001 deg² dropped (except SG), holes ignored,
 * coordinates rounded to 3 dp for SG/MY/BN (the Johor Strait is ~1 km wide) and 2 dp elsewhere.
 * Coastal points that fall in the sea are resolved by the snap rule in borders.ts, so coastline detail is not needed.
 */
import { readFileSync, writeFileSync } from "node:fs";

const URL_10M =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_10m_admin_0_countries.geojson";
const SEA = { SGP: "SG", MYS: "MY", IDN: "ID", THA: "TH", VNM: "VN", PHL: "PH", LAO: "LA", KHM: "KH", MMR: "MM", BRN: "BN", TLS: "TL" };

const src = process.argv[2]
  ? JSON.parse(readFileSync(process.argv[2], "utf8"))
  : await (await fetch(URL_10M)).json();

function dp(pts, tol) {
  if (pts.length < 3) return pts;
  const keep = new Array(pts.length).fill(false);
  keep[0] = keep[pts.length - 1] = true;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = pts[a];
    const [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay, L = Math.hypot(dx, dy);
    let best = -1, bi = -1;
    for (let i = a + 1; i < b; i++) {
      const [px, py] = pts[i];
      const d = L > 0 ? Math.abs(dy * px - dx * py + bx * ay - by * ax) / L : Math.hypot(px - ax, py - ay);
      if (d > best) { best = d; bi = i; }
    }
    if (best > tol) { keep[bi] = true; stack.push([a, bi], [bi, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}
const area = (r) => Math.abs(r.slice(0, -1).reduce((s, p, i) => s + p[0] * r[i + 1][1] - r[i + 1][0] * p[1], 0)) / 2;

const out = {};
let vertices = 0;
for (const f of src.features) {
  const iso = f.properties.ADM0_A3 ?? f.properties.ISO_A3;
  const cc = SEA[iso];
  if (!cc) continue;
  const g = f.geometry;
  const polys = g.type === "MultiPolygon" ? g.coordinates : [g.coordinates];
  const tol = cc === "SG" ? 0.005 : 0.02;
  const nd = ["SG", "MY", "BN"].includes(cc) ? 3 : 2;
  const f10 = 10 ** nd;
  const rings = [];
  for (const poly of polys) {
    const outer = poly[0];
    if (cc !== "SG" && area(outer) < 0.001) continue;
    const s = dp(outer, tol);
    if (s.length < 4) continue;
    rings.push(s.flatMap(([x, y]) => [Math.round(x * f10) / f10, Math.round(y * f10) / f10]));
    vertices += s.length;
  }
  out[cc] = rings;
}

const header = `/* eslint-disable */
// GENERATED by scripts/make-borders.mjs from Natural Earth 1:10m admin-0 countries (public domain).
// Simplified land polygons, flat [lon, lat, lon, lat, ...] rings, outer rings only. ${vertices} vertices. Do not edit.
import type { CountryCode } from "./types.js";

export const BORDERS: Record<CountryCode, number[][]> = `;
writeFileSync(new URL("../src/countries/borders-data.ts", import.meta.url), header + JSON.stringify(out) + ";\n");
console.log(`wrote borders-data.ts: ${vertices} vertices`);
