package sg.hazenow.data

import android.content.Context
import sg.hazenow.BuildConfig
import sg.hazenow.core.ApiResponse
import sg.hazenow.core.HazeApi
import sg.hazenow.core.HazeCore
import java.io.IOException
import java.time.Duration
import java.time.Instant
import java.time.OffsetDateTime
import java.time.temporal.ChronoUnit

/**
 * Deterministic QA scenarios (debug builds only). Fixtures live in app/src/debug/assets/mock/<scenario>/
 * in raw NEA response shape (generated by tools/gen_mock_fixtures.py). Values are fixed; timestamps are
 * shifted so the newest hour is the latest hour NEA would have published by now.
 */
object MockData {
    val SCENARIOS = listOf(
        "normal", "elevated", "high", "very_high", "south_offline", "all_offline_stale", "rising_fast", "all_clear", "network_error",
    )
    const val NETWORK_ERROR = "network_error"
    private val ANCHOR: Instant = OffsetDateTime.parse("2026-09-28T16:00:00+08:00").toInstant()

    val enabled: Boolean get() = BuildConfig.DEBUG

    class Set(val pm25: ApiResponse, val psi: ApiResponse)

    /** @throws IOException for network_error (mimics data.gov.sg being unreachable). */
    fun load(context: Context, scenario: String, now: Instant = Instant.now()): Set {
        if (scenario == NETWORK_ERROR) throw IOException("Mock: network_error")
        fun read(f: String) = context.assets.open("mock/$scenario/$f").bufferedReader().use { it.readText() }
        val latest = now.minus(Duration.ofMinutes(2)).truncatedTo(ChronoUnit.HOURS)
        val shift = Duration.between(ANCHOR, latest)
        return Set(shift(HazeApi.parse(read("pm25.json")), shift), shift(HazeApi.parse(read("psi.json")), shift))
    }

    private fun shift(r: ApiResponse, d: Duration): ApiResponse {
        fun s(iso: String) = OffsetDateTime.parse(iso).plus(d).atZoneSameInstant(HazeCore.SG_ZONE).toOffsetDateTime().toString()
            .let { if (it.length == 22) it.substring(0, 16) + ":00" + it.substring(16) else it } // keep seconds
        return r.copy(
            data = r.data.copy(
                items = r.data.items.map { item ->
                    val ts = s(item.timestamp)
                    item.copy(timestamp = ts, updatedTimestamp = s(item.updatedTimestamp), date = ts.substring(0, 10))
                },
            ),
        )
    }
}
